import "../globals.css";

import localFont from "next/font/local";

import Footer from "@/components/Footer";
import { Header } from "@/components/Header";

import type { Metadata, Viewport } from "next";

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

export const silkSerif = localFont({
  src: "../fonts/Silk Serif Light.otf",
  variable: "--font-silk-serif",
});

export const silkSerifItalic = localFont({
  src: "../fonts/Silk Serif Light Italic.otf",
  variable: "--font-silk-serif-italic",
});

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  width: "device-width",
};

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkSerif.variable} ${silkSerifItalic.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
