import "../globals.css";

import localFont from "next/font/local";
import { Suspense } from "react";

import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import { fontVariables } from "@/lib/fonts";

import type { Metadata, Viewport } from "next";



export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  width: "device-width",
};

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fontVariables}
      >
        <Suspense>
          <Header />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
