import "../globals.css";

import localFont from "next/font/local";

import type { Metadata } from "next";

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

const silkSerif = localFont({
  src: "../fonts/Silk Serif Light.otf",
  variable: "--font-silk-serif",
});

const silkSerifItalic = localFont({
  src: "../fonts/Silk Serif Light Italic.otf",
  variable: "--font-silk-serif-italic",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkSerif.variable} ${silkSerifItalic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
