import "../globals.css";

import { Head } from "next/document";

import { fontVariables } from "@/lib/fonts";

import type { Metadata } from "next";


export const metadata: Metadata = {
  appleWebApp: {
    title: "Manumaharani",
  },
  description: "Generated by create next app",
  title: "Create Next App"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fontVariables}
      >
        {children}
      </body>
    </html>
  );
}
